FROM python:3.11-slim
WORKDIR /app
RUN apt-get update && apt-get install -y libpq-dev gcc && rm -rf /var/lib/apt/lists/*
COPY backend-tutor/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install gunicorn
COPY backend-tutor/ .
EXPOSE 8000
CMD ["gunicorn", "backend_project.wsgi:application", "--bind", "0.0.0.0:8000"]
